package com.dipendra.test.models;
// Generated 21 Jul 2026, 2:28:59 pm by Hibernate Tools 7.3.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String name;
     private byte age;
     private String email;
     private String city;

    public Users() {
    }

    public Users(String name, byte age, String email, String city) {
       this.name = name;
       this.age = age;
       this.email = email;
       this.city = city;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="age", nullable=false)
    public byte getAge() {
        return this.age;
    }
    
    public void setAge(byte age) {
        this.age = age;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="city", nullable=false, length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


